### ISSUE TITLE
【工作坊】WenYan 文言文编程语言入门

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Wiki#18]
- 主讲人：@demongodYY
- 参考文档：http://wenyan-lang.lingdong.works/

**Comment by Akagilnc** [comment]
666666

**Comment by Akagilnc** [comment]
你问我资瓷不资瓷，我是肯定资瓷的啦

**Comment by demongodYY** [comment]
哈哈哈，估计就我们几个玩玩

**Comment by TechQuery** [comment]
- 文案代码： 2f33a73
- 官网博文： https://fcc-cd.tk/activity/workshop/wenyan-programming/

**Comment by TechQuery** [comment]
FreeCodeCamp-Chengdu/Wiki#20
