### ISSUE TITLE
COSCon'20 成都站 + 开源市集

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Wiki#26]
亲爱的**开源人**：
　　你好！COVID-19 肆虐后的你还好吗？
　　[COSCon（中国开源年会）2020](https://www.bagevent.com/event/6840909) 因为疫情而转为**线上直播**为主的形式，并在北京、上海、深圳、成都、长沙**开设分会场供讲师直播、交流**。
　　在此，**COSCon‘20 成都分会场**的承办方 [FCC 成都社区](https://fcc-cd.dev/)诚挚邀请**西南地区**的开源人：
1. [**投稿讲题**](https://mp.weixin.qq.com/s/D2Ul_bmxhmBwhsYRypqCqw)
2. **布置展位**（参考 [2018 成都 Web 前端大会](https://web-conf.dev/#2018/)「开源市集」）

### 2018 成都 Web 前端大会

https://mp.weixin.qq.com/s/iQxdcRHG_9vXXE0OeMJE5g

#### WebCell 展位
![](https://user-images.githubusercontent.com/19969570/94335054-43f98b80-000b-11eb-9417-9849b440991a.png)

#### Deepin 展位
![](https://user-images.githubusercontent.com/19969570/94335065-61c6f080-000b-11eb-9781-9d7ba2de0def.png)

### 2019 成都 Web 全栈大会

https://covariant.cn/2019/11/19/covscript3-3-release/

#### 项目展位
![](https://covariant.cn/wp-content/uploads/2019/11/a-2.jpg)

#### 闪电演讲
![](https://covariant.cn/wp-content/uploads/2019/11/IMG_0916-1024x576.jpg)

## 报名方式

- **演讲主题**：http://www.wenjuan.in/s/e2EJniQ/
- **开源市集**：在本 issue 下回复
  1. 您想展示的**开源项目**、**开源组织**、**开放社群**概况
  2. 您的**联系方式**

**Comment by LiJiahaoCoder** [comment]
## C++

**Comment by miyaliu666** [comment]
## Markdown

**Comment by LiJiahaoCoder** [comment]
## TS

@timonwong
@trotyl

**Comment by LiJiahaoCoder** [comment]
## Go

**Comment by Cute233** [comment]
### JavaScript
1. @egoist
> 组织：（1）[https://github.com/vuejs](url)（2） [https://github.com/LightBulb](url) （3） [https://github.com/saojs](url)
-  邮箱： 0x142857@gmail.com 
- [https://egoist.sh](url)

2. @mycolorway
http://www.mycolorway.com

3. @zuiidea 
4. @dontcontactme  (404了)
5. @longbill
6. @huacnlee
7. @yuanchuan
8. @lypeer
9. @gaoryrt
10. @togayther
11. @chxj1992
12. @bumaociyuan
13. @gucong3000
14. @tossshinhwa
15. @jimmylv
16. @just4fun
17. @aprilorange （404了）
18. @morlay
19. @iwgang
20. @xingbofeng
21. @weidagang
22. @fanpei91
23. @heroicyang
24. @yangmingshan
25. @anzhihun

**Comment by yangmingshan** [comment]
报名参加开源市集🙋‍♂️
- 开源项目：[Vue Mini](https://github.com/vue-mini/vue-mini)
- 联系方式：y.mingshan3@gmail.com

**Comment by Cute233** [comment]
### **C**
1. @bingoogolapple       （ @美团点评 ）  
bingoogolapple@gmail.com
http://www.bingoogolapple.cn
2. @huacnlee   （在JS时，已发邮件）
huacnlee@gmail.com 
https://huacnlee.com
3. @cppla
邮箱： i@cpp.lai
https://cpp.la
4. @tomwillow
tomwillow@qq.com
5. @xtaci
imap@live.com
6. @paladin-t
https://paladin-t.github.io/ ♥
推特： @wangrenxin
7. @peimin（有排行无项目？）
8. @shuax
admin@shuax.com
https://shuax.com
9. @dake
项目： PixelCyber​​.com
apps@pixelcyber.com

**Comment by TechQuery** [comment]
## 总结文章
- 代码提交： caa7fbc
- 访问地址： https://fcc-cd.dev/article/summary/a-solitary-spark-and-wars-begin/
