### ISSUE TITLE
【分享会】应用开发之王 —— Web 标准技术

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Wiki#30]
## 内容提纲

- 网页制作 N 剑客
- 闪客帝国
- “给我做个 H5”
- “我要做个小程序”
- 日新月异的 Web 标准
  - Web Components
  - PWA
  - Web USB
  - Web Authn
  - Web RTC
  - 弹幕标准
  - WoT
  - Web XR

## 活动信息

- 时间：2020年12月26日 19:00~21:00
- 地点：
  - 会议室：https://meeting.tencent.com/p/3840877398
  - 直播间：https://live.bilibili.com/22218677
- 合办：[智锐科创计算机协会 四川大学分会](https://covariant.cn/scu/)

**Comment by HUGHNew** [comment]
海报：[poster](https://gitee.com/HughNew/Photos/raw/master/FCC/poster.png)
技术路线图： [roadmap](https://gitee.com/HughNew/Photos/raw/master/FCC/roadmap.png)

**Comment by HUGHNew** [comment]
海报： ![poster](https://gitee.com/HughNew/Photos/raw/master/FCC/poster.png)
宣传技术路线图： ![roadmap](https://gitee.com/HughNew/Photos/raw/master/FCC/roadmap.png)

**Comment by HUGHNew** [comment]
海报链接 <https://gitee.com/HughNew/Photos/raw/master/FCC/poster.png>
或者
![poster](https://github.com/HUGHNew/PictureBed/raw/main/FCC/poster.png)
<https://github.com/HUGHNew/PictureBed/raw/main/FCC/poster.png>

**Comment by HUGHNew** [comment]
![image](https://user-images.githubusercontent.com/52786639/102890323-367f6080-4497-11eb-902b-4fac2e4d5794.png)
alright, do it third time

**Comment by TechQuery** [comment]
![image](https://user-images.githubusercontent.com/19969570/103153848-95faaa80-47ce-11eb-978f-fbad2d56938d.png)

**Comment by TechQuery** [comment]
- PPT 原文提交： 3d1ce3c
- 活动内容网址： https://fcc-cd.dev/activity/salon/web-standard-app-development/
