### ISSUE TITLE
【工作坊】AI 学院 - 超级英雄识别

### ISSUE THREAD

**Issue by Akagilnc** [FreeCodeCamp-Chengdu/Wiki#5]
- [x] [文案](https://fcc-cd.tk/activity/workshop/school-of-ai-1/)
- [x] 现场
- [ ] 回顾

**Comment by TechQuery** [comment]
- 代码提交： 4d90db4
- 官网博文： https://fcc-cd.tk/activity/workshop/school-of-ai-1/
