### ISSUE TITLE
【大会】成都全栈大会

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/Wiki#7]
## 会议日程

- 时间：2019 年 11 月某周末 2 天
- 地点：天府软件园 x 区

### 主题演讲（主会场上午）

|              标题              |      讲师       |            讲师简介             |
| :----------------------------: | :-------------: | :-----------------------------: |
| 贸易战给中国开源界的挑战与机遇 |    @tedliu1     | 开源社理事长、Apache 基金会成员 |
|    Anti 996, Data as Labor     | @Tedko @kattgu7 |         996.ICU 创始人          |
|     SOLID —— 万维网的未来      |     @leinue     |       SOLID 中文网创始人        |
|   [公益技术社区的术与道][1]    |   @TechQuery    |   freeCodeCamp 成都社区负责人   |

### 动手实践（分会场下午）

|              标题              |          讲师          |                  讲师简介                   |
| :----------------------------: | :--------------------: | :-----------------------------------------: |
|  Web Components 应用开发实战   |       @TechQuery       |         freeCodeCamp 成都社区负责人         |
|       Web Authn 体验工坊       |                        |                                             |
|        PWA 应用开发实战        |       @TechQuery       |         freeCodeCamp 成都社区负责人         |
|          Web Assembly          |      @Becavalier       |         freeCodeCamp 上海社区负责人         |
|         WoT（万物网）          |       @akira-cn        | 360 奇舞团掌门人、[《从物联到万联》][2]译者 |
|          React hooks           |                        |                                             |
| **数据可视化**经典图形绘图算法 |                        |                                             |
|            Flutter             |                        |              Flutter 成都社区               |
| [Node.JS TSC Code & Learn][3]  | @joyeecheung @XadillaX |           Node.JS 技术委员会成员            |
|         Deno 体验工坊          |      @manyuanrong      |         ThoughtWorks Web 前端工程师         |
|       .Net Core 体验工坊       |        @ltm0203        |            微软 MVP、52ABP 作者             |
|           敏捷训练营           |     @ThoughtWorks      |           ThoughtWorks 成都办公室           |
|           STEM 教育            |                        |                                             |
|            开源硬件            |                        |                                             |

## 合作伙伴

|         名称         |               简介                |
| :------------------: | :-------------------------------: |
| @freeCodeCamp Global |    全球最大的公益编程学习平台     |
|      Node Party      |                                   |
|       宝尊电商       |                                   |
|        掘金网        |                                   |
|       微软 MVP       |       微软“最有价值专家”社区        |
|        Deepin        | 全球最受欢迎的中文 Linux 操作系统 |

[1]: https://fcc-cd.tk/profile/guide/slide.html
[2]: https://book.douban.com/subject/27624444/
[3]: https://github.com/nodejs/code-and-learn/issues

**Comment by Tedko** [comment]
😯

**Comment by TechQuery** [comment]
https://github.com/orgs/FreeCodeCamp-Chengdu/projects/3?fullscreen=true
