### ISSUE TITLE
【工作坊】程序员英语学习

### ISSUE THREAD

**Issue by demongodYY** [FreeCodeCamp-Chengdu/Wiki#9]
- 主旨：英语是程序开发中必不可少的技能

## 筹备
- [ ] 联系 @茉莉花树 ，确定内容、形式

**Comment by TechQuery** [comment]
FCC 国际站[新课程](https://learn.freecodecamp.org/)、[编程语言指南](https://guide.freecodecamp.org/)、[新闻](https://www.freecodecamp.org/news/)、[视频](https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ)等需翻译成中文，可以**翻译学习资源**为主题开办**英语工作坊**，边学边贡献~

**Comment by TechQuery** [comment]
- 代码提交 bc92581
- 活动文案 https://fcc-cd.tk/activity/workshop/fcc-technical-translation-0/
- 活动回顾 https://fcc-cd.tk/article/fcc-technical-translation-0/
- 活动总结 https://fcc-cd.tk/article/fcc-translation-workshop-0/
