### ISSUE TITLE
文章时间问题

### ISSUE THREAD

**Issue by dethan3** [FreeCodeCamp-Chengdu/Wiki#97]
我认为这篇文章 https://fcc-cd.dev/article/translation/index.html/ 在网站上显示的时间是错误的，包括文件名称也不应该是 `index.html.md` 
我查看了这篇文章的提交时间在上个月，但网站上显示在 4天前。
https://github.com/FreeCodeCamp-Chengdu/Wiki/commit/3f7a7859ecead2a9f9bce7a11a1655b4f8db4004

**Comment by TechQuery** [comment]
1. 爬虫只截取网址的最后一节作为文件名，`index.html` 这一类特殊的可以省略的文件名可以忽略（需要在上游 action 改）

2. 旧版爬虫没有文章日期分析功能，就不会在 Markdown 里写入 `date` 原数据，这个静态网站生成框架就会自动用最新时间。

现在新版爬虫会把没翻译的文章都放到 `_draft` 文件夹（草稿箱），线上就不会显示出来了。但之前爬的文章不但要都移到草稿箱，还要在每个 issue 上改一下编辑入口网址，这个你能做吗？

**Comment by dethan3** [comment]
> 1. 爬虫只截取网址的最后一节作为文件名，`index.html` 这一类特殊的可以省略的文件名可以忽略（需要在上游 action 改）
> 2. 旧版爬虫没有文章日期分析功能，就不会在 Markdown 里写入 `date` 原数据，这个静态网站生成框架就会自动用打包构建的时间。
> 
> 现在新版爬虫会把没翻译的文章都放到 `_draft` 文件夹（草稿箱），线上就不会显示出来了。但之前爬的文章不但要都移到草稿箱，还要在每个 issue 上改一下编辑入口网址，这个你能做吗？

没问题，这个我来做
